### ISSUE TITLE
Converting DTM topic models object not working

### ISSUE THREAD

**Issue by hawc2** [ekstroem/Austin#2]
I'm trying to use Austin with [Wordfish](http://www.wordfish.org/), but Austin won’t covert the topicmodels DTM object into the Wordfish model. Keep getting error messages that says DTM does not have row and column names. We've contacted the wordfish developers and not gotten a response, but think it may relate to versioning with Austin?

**Comment by ekstroem** [comment]
You'll need to be more specific about what goes wrong and what would be right if I should have a chance to look at it

**Comment by hawc2** [comment]
Apologies for the delay - we ended up switching to Quanteda to address this problem
